### PR TITLE
shpkg 1.1.0

### PR DESCRIPTION
**Pull request by GrpeApple**
If you have noticed, I did not change the version on the commits (as I am still unsure).
But, here is a summary for all my commits:
<ul>
  <li>Enable bash strict mode</li>
  <ul>
    <li>
      <code>set -euo pipefail</code> <a href="http://redsymbol.net/articles/unofficial-bash-strict-mode">See unofficial bash strict mode</a>
    </li>
  <li>
    <code>$1</code> and <code>$2</code> are replaced with <code>${1:-}</code> and <code>${2:-}</code> respectively.
    <details>
      <summary>Positional parameters</summary>
      <a href="http://redsymbol.net/articles/unofficial-bash-strict-mode">
        Image showing positional parameters
      </a>
   </details>
  </ul>
  <li>Fill in missing colors for missing tput</li>
  <ul>
    <li>
      When <code>ncurses-utils</code> is missing, I replaced the empty values with <a href="https://gist.github.com/RabaDabaDoba/145049536f815903c79944599c6f952a#file-bash-colors-md">ANSI Color Codes</a>
    </li>
    <ul>
      <li>
        I have also replaced <code><i>${COLOR}</i>${BOLD}</code> with <code>${B<i>COLOR</i>:-<i>${COLOR}</i>${BOLD}}</code>
      </li>
    </ul>
  </ul>
  <li>Minor explicit redirection of stdout to /dev/null</li>
  <ul>
    <li>
      <code>>/dev/null 2>&1</code> is prepended with <code>1</code> (<code>1>/dev/null 2>&1</code>)
    </li>
  </ul>
  <li>Check if a file exists instead of checking if a regular file exists</li>
  <ul>
    <li>
      <code>-e</code> is used instead of <code>-f</code> to follow any file. In other words, <code>-f</code> tests if a file is a regular file and exists; <code>-e</code> tests if a file exists.
    </li>
  </ul>
</ul>

### CODE REVIEW

**Comment by WMCB-Tech** [comment]
Nice, merging the PR

**Comment by WMCB-Tech** [comment]
I have noticed that when `-u` set in bash strict mode, some unset variables would cause the script to break like this for example:

```
./shpkg: line 206: shpkg_distro_only: unbound variable
```

Probably would be better if not using `-u` mode at the moment or adjust it's variable

**Comment by WMCB-Tech** [comment]
yeah, that is probably better

**Comment by GrpeApple** [comment]
And I know there is a lot of variables, but I think I can manage that.

**Comment by GrpeApple** [comment]
I did not notice your message, I was using <code>gh</code> in Termux.

**Comment by GrpeApple** [comment]
Also, I have noticed at line <code>299</code> (and other lines) that you did not quote them. (and will result in word splitting, which is fine. But also globbing, which can be a bit dangerous)
Perhaps use <code>eval "${SHPKG_SUDO} ${SHPKG_INSTALL} ${shpkg_build_depends:-}"</code>?

**Comment by WMCB-Tech** [comment]
>  Perhaps use `eval "${SHPKG_SUDO} ${SHPKG_INSTALL} ${shpkg_build_depends:-}"`?
@GrpeApple yeah if that's suitable

**Comment by GrpeApple** [comment]
Summary for my last commits:
<ul>
	<li>Double-quote variables</li>
	<ul>
		<li>
			Exactly what the commit says, and added <code>eval</code> for some variables (commands)
		</li>
	</ul>
	<li>Make read mangle backslashes</li>
	<ul>
		<li>
			Add <code>-r</code> option for <code>read</code> which does not allow backslashes to escape certain characters.
		</li>
	</ul>
	<li>Avoid most unbound variables</li>
	<ul>
		<li>
			Notice I said 'most', that is because I have not tested it yet.
			But in this commit, I added <code>:-</code> to most of the variables (<code>${<i>variable</i>:-<}</code>) to avoid getting an unbound variable error from <code>set -u</code>.
		</li>
	</ul>
</ul>

**Comment by GrpeApple** [comment]
Just like the summary above, this applies to the last commit.

**Comment by WMCB-Tech** [comment]
Suggesting instead of having `BRED` `BGREEN` variables, it should fallback to ANSI escape codes if the script detects if there's no tput command

Just
```
RED, GREEN, BOLD, BOLDONLY, NOATTR
```

Would be enough, unless there's a problem with it

**Comment by WMCB-Tech** [comment]
> I have also replaced `${COLOR}${BOLD}` with `${BCOLOR:-${COLOR}${BOLD}}`

I'll probably add a variable for some build scripts to use Ansi Color variables to avoid unbound variable errors

**Comment by GrpeApple** [comment]
Since you do not have any unbold colors, why not merged it into one?

**Comment by WMCB-Tech** [comment]
You mean combining all variables instead?

**Comment by GrpeApple** [comment]
And, you can always <code>NOATTR</code> in the <code>tput</code> colors.

**Comment by WMCB-Tech** [comment]
Alright, i guess it should be combined instead

**Comment by GrpeApple** [comment]
Working on it... Also, should we bump the version to `1.1.0`?

**Comment by WMCB-Tech** [comment]
Good idea, as probably the commits are probably a lot

**Comment by GrpeApple** [comment]
I will probably open up a pull-request for the colors.

**Comment by WMCB-Tech** [comment]
Alright, good idea

**Comment by GrpeApple** [comment]
> > I have also replaced `${COLOR}${BOLD}` with `${BCOLOR:-${COLOR}${BOLD}}`
> 
> I'll probably add a variable for some build scripts to use Ansi Color variables to avoid unbound variable errors such as
> 
> `${RED}${BOLD}some text${NOATTR}`
> 
> is being used but the current build scripts dosen't know about it
> 
> Or I'll edit build scripts instead to follow that variable

I got confused, what do you mean by this?

**Comment by GrpeApple** [comment]
Also, my pull request seems to be ready.

**Comment by WMCB-Tech** [comment]
> I got confused, what do you mean by this?

Nvm about it after merging color environment variables

**Comment by GrpeApple** [comment]
I feel like this is ready for merging.

**Pull request merged**
